POST http://localhost:8444/api/seed
###
POST http://localhost:8444/api/login HTTP/1.1
content-type: application/json

{
    "email": "garrett@bull.com",
    "password": "NoMorePests1!"
}
###
GET http://localhost:8444/private
###
GET http://localhost:8444/logout
###
GET http://localhost:8444/api/appts
###