POST http://localhost:8444/api/seed
###
GET http://localhost:8444/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbnlAc3RhcmtlbnQuY29tIiwicGFzc3dvcmQiOiIxTHV2UGVwcGVyISIsImlhdCI6MTY2Njc5NzMwOH0.RRC4yIapIE8Uzu_o45knsrVw051Y5QzQkbVHLHKgBnc
###
GET http://localhost:8444/api/getallappts
###